management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 7000
  
spring:
  application:
    name: Consumer-Service
    
  cloud:
    consul:
      host: http://discovery
      port: 8500
  zipkin:
    base-url: http://zipkin:9411/
    
resilience4j:
  retry:
    instances:
      bookSearch:
        wait-duration: 5s #This will make resilience4J to wait 5 sec
        max-attempts: 2
      authorSearch:
        wait-duration: 5s
        max-attempts: 2
