server:
  port: ${random.int[8000,9000]}
  
  
spring:
  h2:
    console: 
      enabled: true
      path: /h2
  datasource: 
    url: jdbc:h2:mem:bookdb
    username: lib
    password: 
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  application:
    name: Book-Service
    
management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - info
        - health
