server:
  port: 5052

spring:
  application:
    name: Aggregator-Service
  cloud:
    consul:
      host: http://discovery
      port: 8500
  zipkin:
    base-url: http://zipkin:9411/


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
resilience4j:
  retry:
    instances:
      bookSearch:
        wait-duration: 5s #This will make resilience4J to wait 5 sec
        max-attempts: 2
      authorSearch:
        wait-duration: 5s
        max-attempts: 2