server:
  port: 5052

spring:
  application:
    name: Aggregator-Service
    
    
management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - info
        - health